<div class="moz-text-flowed" style="font-family: -moz-fixed">0.0:Wacht op de gebruiker om een toets in te drukken, van een keuzelijst
0.1:keuzes
0.2:tekst
0.3:Geeft de toelaatbare toetsen aan.  Standaard is:
0.4:Geef de keuzetoetsen niet weer aan het einde van de prompt
0.5:instellen om hoofdlettergevoelig zijn
0.6:**Genegeerd, voor compatibiliteit met MS-DOS
0.7:De als de prompt weer te geven tekst
0.8:Luidt een alarmtoon/waarschuwing (biep) op de prompt
3.0:jn

</div>